@echo off
cd /d "%~dp0"
echo Starting backend server...
start "Backend Server" cmd /k "cd backend && npm start"
timeout /t 3 /nobreak > nul
echo Starting frontend server...
start "Frontend Server" cmd /k "cd frontend && npm run dev"
echo Both servers are starting in separate windows...
